In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv(r'C:\Users\hp\Downloads\Project_1.csv')
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,LP002911,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,LP002912,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
589,LP002926,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
590,LP002928,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban,Y
591,LP002931,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
592,LP002933,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
593,LP002936,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,Y
594,LP002938,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,LP002943,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
598,LP002945,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
604,LP002959,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,LP002960,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [5]:
##droping loan_id column
df.drop(['Loan_ID'],axis=1,inplace=True)
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
584,Male,Yes,1,Graduate,No,2787,1917.0,146.0,360.0,0.0,Rural,N
585,Male,Yes,1,Graduate,No,4283,3000.0,172.0,84.0,1.0,Rural,N
586,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
589,Male,Yes,2,Graduate,Yes,2726,0.0,106.0,360.0,0.0,Semiurban,N
590,Male,Yes,0,Graduate,No,3000,3416.0,56.0,180.0,1.0,Semiurban,Y
591,Male,Yes,2,Graduate,Yes,6000,0.0,205.0,240.0,1.0,Semiurban,N
592,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
593,Male,Yes,0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural,Y
594,Male,Yes,0,Graduate,Yes,16120,0.0,260.0,360.0,1.0,Urban,Y
595,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
597,Male,No,NaN,Graduate,No,2987,0.0,88.0,360.0,0.0,Semiurban,N
598,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
600,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
604,Female,Yes,1,Graduate,No,12000,0.0,496.0,360.0,1.0,Semiurban,Y
605,Male,Yes,0,Not Graduate,No,2400,3800.0,NaN,180.0,1.0,Urban,N
606,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [6]:
##encoding columns
dummies=pd.get_dummies(df,columns=['Gender','Education','Property_Area'],prefix=['gender','education','property_area'])
dummies

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,No,0,No,5849,0.0,NaN,360.0,1.0,Y,0,1,1,0,0,0,1
1,Yes,1,No,4583,1508.0,128.0,360.0,1.0,N,0,1,1,0,1,0,0
2,Yes,0,Yes,3000,0.0,66.0,360.0,1.0,Y,0,1,1,0,0,0,1
3,Yes,0,No,2583,2358.0,120.0,360.0,1.0,Y,0,1,0,1,0,0,1
4,No,0,No,6000,0.0,141.0,360.0,1.0,Y,0,1,1,0,0,0,1
5,Yes,2,Yes,5417,4196.0,267.0,360.0,1.0,Y,0,1,1,0,0,0,1
6,Yes,0,No,2333,1516.0,95.0,360.0,1.0,Y,0,1,0,1,0,0,1
7,Yes,3+,No,3036,2504.0,158.0,360.0,0.0,N,0,1,1,0,0,1,0
8,Yes,2,No,4006,1526.0,168.0,360.0,1.0,Y,0,1,1,0,0,0,1
9,Yes,1,No,12841,10968.0,349.0,360.0,1.0,N,0,1,1,0,0,1,0
10,Yes,2,No,3200,700.0,70.0,360.0,1.0,Y,0,1,1,0,0,0,1
11,Yes,2,NaN,2500,1840.0,109.0,360.0,1.0,Y,0,1,1,0,0,0,1
12,Yes,2,No,3073,8106.0,200.0,360.0,1.0,Y,0,1,1,0,0,0,1
13,No,0,No,1853,2840.0,114.0,360.0,1.0,N,0,1,1,0,1,0,0
14,Yes,2,No,1299,1086.0,17.0,120.0,1.0,Y,0,1,1,0,0,0,1
15,No,0,No,4950,0.0,125.0,360.0,1.0,Y,0,1,1,0,0,0,1
16,No,1,No,3596,0.0,100.0,240.0,NaN,Y,0,1,0,1,0,0,1
17,No,0,No,3510,0.0,76.0,360.0,0.0,N,1,0,1,0,0,0,1
18,Yes,0,No,4887,0.0,133.0,360.0,1.0,N,0,1,0,1,1,0,0
19,Yes,0,NaN,2600,3500.0,115.0,NaN,1.0,Y,0,1,1,0,0,0,1
20,Yes,0,No,7660,0.0,104.0,360.0,0.0,N,0,1,0,1,0,0,1
21,Yes,1,No,5955,5625.0,315.0,360.0,1.0,Y,0,1,1,0,0,0,1
22,Yes,0,No,2600,1911.0,116.0,360.0,0.0,N,0,1,0,1,0,1,0
23,Yes,2,No,3365,1917.0,112.0,360.0,0.0,N,0,0,0,1,1,0,0
24,Yes,1,NaN,3717,2925.0,151.0,360.0,NaN,N,0,1,1,0,0,1,0
25,Yes,0,Yes,9560,0.0,191.0,360.0,1.0,Y,0,1,1,0,0,1,0
26,Yes,0,No,2799,2253.0,122.0,360.0,1.0,Y,0,1,1,0,0,1,0
27,Yes,2,No,4226,1040.0,110.0,360.0,1.0,Y,0,1,0,1,0,0,1
28,No,0,No,1442,0.0,35.0,360.0,1.0,N,0,1,0,1,0,0,1
29,No,2,NaN,3750,2083.0,120.0,360.0,1.0,Y,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,Yes,1,No,2787,1917.0,146.0,360.0,0.0,N,0,1,1,0,1,0,0
585,Yes,1,No,4283,3000.0,172.0,84.0,1.0,N,0,1,1,0,1,0,0
586,Yes,0,No,2297,1522.0,104.0,360.0,1.0,Y,0,1,1,0,0,0,1
587,No,0,No,2165,0.0,70.0,360.0,1.0,Y,1,0,0,1,0,1,0
588,No,0,No,4750,0.0,94.0,360.0,1.0,Y,0,0,1,0,0,1,0
589,Yes,2,Yes,2726,0.0,106.0,360.0,0.0,N,0,1,1,0,0,1,0
590,Yes,0,No,3000,3416.0,56.0,180.0,1.0,Y,0,1,1,0,0,1,0
591,Yes,2,Yes,6000,0.0,205.0,240.0,1.0,N,0,1,1,0,0,1,0
592,No,3+,Yes,9357,0.0,292.0,360.0,1.0,Y,0,0,1,0,0,1,0
593,Yes,0,No,3859,3300.0,142.0,180.0,1.0,Y,0,1,1,0,1,0,0
594,Yes,0,Yes,16120,0.0,260.0,360.0,1.0,Y,0,1,1,0,0,0,1
595,No,0,No,3833,0.0,110.0,360.0,1.0,Y,0,1,0,1,1,0,0
596,Yes,2,Yes,6383,1000.0,187.0,360.0,1.0,N,0,1,0,1,1,0,0
597,No,NaN,No,2987,0.0,88.0,360.0,0.0,N,0,1,1,0,0,1,0
598,Yes,0,Yes,9963,0.0,180.0,360.0,1.0,Y,0,1,1,0,1,0,0
599,Yes,2,No,5780,0.0,192.0,360.0,1.0,Y,0,1,1,0,0,0,1
600,No,3+,NaN,416,41667.0,350.0,180.0,NaN,N,1,0,1,0,0,0,1
601,Yes,0,NaN,2894,2792.0,155.0,360.0,1.0,Y,0,1,0,1,1,0,0
602,Yes,3+,No,5703,0.0,128.0,360.0,1.0,Y,0,1,1,0,0,0,1
603,No,0,No,3676,4301.0,172.0,360.0,1.0,Y,0,1,1,0,1,0,0
604,Yes,1,No,12000,0.0,496.0,360.0,1.0,Y,1,0,1,0,0,1,0
605,Yes,0,No,2400,3800.0,NaN,180.0,1.0,N,0,1,0,1,0,0,1
606,Yes,1,No,3400,2500.0,173.0,360.0,1.0,Y,0,1,1,0,0,1,0
607,Yes,2,No,3987,1411.0,157.0,360.0,1.0,Y,0,1,0,1,1,0,0
608,Yes,0,No,3232,1950.0,108.0,360.0,1.0,Y,0,1,1,0,1,0,0
609,No,0,No,2900,0.0,71.0,360.0,1.0,Y,1,0,1,0,1,0,0
610,Yes,3+,No,4106,0.0,40.0,180.0,1.0,Y,0,1,1,0,1,0,0
611,Yes,1,No,8072,240.0,253.0,360.0,1.0,Y,0,1,1,0,0,0,1
612,Yes,2,No,7583,0.0,187.0,360.0,1.0,Y,0,1,1,0,0,0,1
613,No,0,Yes,4583,0.0,133.0,360.0,0.0,N,1,0,1,0,0,1,0

In [7]:
columns=['Gender','Education','Property_Area']
df=pd.concat([df,dummies],axis=1)
df.drop(columns,axis=1,inplace=True)

In [8]:
df

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Married,...,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,No,0,No,5849,0.0,NaN,360.0,1.0,Y,No,...,360.0,1.0,Y,0,1,1,0,0,0,1
1,Yes,1,No,4583,1508.0,128.0,360.0,1.0,N,Yes,...,360.0,1.0,N,0,1,1,0,1,0,0
2,Yes,0,Yes,3000,0.0,66.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
3,Yes,0,No,2583,2358.0,120.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,0,1,0,0,1
4,No,0,No,6000,0.0,141.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,1,1,0,0,0,1
5,Yes,2,Yes,5417,4196.0,267.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
6,Yes,0,No,2333,1516.0,95.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,0,1,0,0,1
7,Yes,3+,No,3036,2504.0,158.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,1,1,0,0,1,0
8,Yes,2,No,4006,1526.0,168.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
9,Yes,1,No,12841,10968.0,349.0,360.0,1.0,N,Yes,...,360.0,1.0,N,0,1,1,0,0,1,0
10,Yes,2,No,3200,700.0,70.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
11,Yes,2,NaN,2500,1840.0,109.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
12,Yes,2,No,3073,8106.0,200.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
13,No,0,No,1853,2840.0,114.0,360.0,1.0,N,No,...,360.0,1.0,N,0,1,1,0,1,0,0
14,Yes,2,No,1299,1086.0,17.0,120.0,1.0,Y,Yes,...,120.0,1.0,Y,0,1,1,0,0,0,1
15,No,0,No,4950,0.0,125.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,1,1,0,0,0,1
16,No,1,No,3596,0.0,100.0,240.0,NaN,Y,No,...,240.0,NaN,Y,0,1,0,1,0,0,1
17,No,0,No,3510,0.0,76.0,360.0,0.0,N,No,...,360.0,0.0,N,1,0,1,0,0,0,1
18,Yes,0,No,4887,0.0,133.0,360.0,1.0,N,Yes,...,360.0,1.0,N,0,1,0,1,1,0,0
19,Yes,0,NaN,2600,3500.0,115.0,NaN,1.0,Y,Yes,...,NaN,1.0,Y,0,1,1,0,0,0,1
20,Yes,0,No,7660,0.0,104.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,1,0,1,0,0,1
21,Yes,1,No,5955,5625.0,315.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
22,Yes,0,No,2600,1911.0,116.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,1,0,1,0,1,0
23,Yes,2,No,3365,1917.0,112.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,0,0,1,1,0,0
24,Yes,1,NaN,3717,2925.0,151.0,360.0,NaN,N,Yes,...,360.0,NaN,N,0,1,1,0,0,1,0
25,Yes,0,Yes,9560,0.0,191.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,1,0
26,Yes,0,No,2799,2253.0,122.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,1,0
27,Yes,2,No,4226,1040.0,110.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,0,1,0,0,1
28,No,0,No,1442,0.0,35.0,360.0,1.0,N,No,...,360.0,1.0,N,0,1,0,1,0,0,1
29,No,2,NaN,3750,2083.0,120.0,360.0,1.0,Y,No,...,360.0,1.0,Y,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,Yes,1,No,2787,1917.0,146.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,1,1,0,1,0,0
585,Yes,1,No,4283,3000.0,172.0,84.0,1.0,N,Yes,...,84.0,1.0,N,0,1,1,0,1,0,0
586,Yes,0,No,2297,1522.0,104.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
587,No,0,No,2165,0.0,70.0,360.0,1.0,Y,No,...,360.0,1.0,Y,1,0,0,1,0,1,0
588,No,0,No,4750,0.0,94.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,0,1,0,0,1,0
589,Yes,2,Yes,2726,0.0,106.0,360.0,0.0,N,Yes,...,360.0,0.0,N,0,1,1,0,0,1,0
590,Yes,0,No,3000,3416.0,56.0,180.0,1.0,Y,Yes,...,180.0,1.0,Y,0,1,1,0,0,1,0
591,Yes,2,Yes,6000,0.0,205.0,240.0,1.0,N,Yes,...,240.0,1.0,N,0,1,1,0,0,1,0
592,No,3+,Yes,9357,0.0,292.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,0,1,0,0,1,0
593,Yes,0,No,3859,3300.0,142.0,180.0,1.0,Y,Yes,...,180.0,1.0,Y,0,1,1,0,1,0,0
594,Yes,0,Yes,16120,0.0,260.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
595,No,0,No,3833,0.0,110.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,1,0,1,1,0,0
596,Yes,2,Yes,6383,1000.0,187.0,360.0,1.0,N,Yes,...,360.0,1.0,N,0,1,0,1,1,0,0
597,No,NaN,No,2987,0.0,88.0,360.0,0.0,N,No,...,360.0,0.0,N,0,1,1,0,0,1,0
598,Yes,0,Yes,9963,0.0,180.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,1,0,0
599,Yes,2,No,5780,0.0,192.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
600,No,3+,NaN,416,41667.0,350.0,180.0,NaN,N,No,...,180.0,NaN,N,1,0,1,0,0,0,1
601,Yes,0,NaN,2894,2792.0,155.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,0,1,1,0,0
602,Yes,3+,No,5703,0.0,128.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
603,No,0,No,3676,4301.0,172.0,360.0,1.0,Y,No,...,360.0,1.0,Y,0,1,1,0,1,0,0
604,Yes,1,No,12000,0.0,496.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,1,0,1,0,0,1,0
605,Yes,0,No,2400,3800.0,NaN,180.0,1.0,N,Yes,...,180.0,1.0,N,0,1,0,1,0,0,1
606,Yes,1,No,3400,2500.0,173.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,1,0
607,Yes,2,No,3987,1411.0,157.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,0,1,1,0,0
608,Yes,0,No,3232,1950.0,108.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,1,0,0
609,No,0,No,2900,0.0,71.0,360.0,1.0,Y,No,...,360.0,1.0,Y,1,0,1,0,1,0,0
610,Yes,3+,No,4106,0.0,40.0,180.0,1.0,Y,Yes,...,180.0,1.0,Y,0,1,1,0,1,0,0
611,Yes,1,No,8072,240.0,253.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
612,Yes,2,No,7583,0.0,187.0,360.0,1.0,Y,Yes,...,360.0,1.0,Y,0,1,1,0,0,0,1
613,No,0,Yes,4583,0.0,133.0,360.0,0.0,N,No,...,360.0,0.0,N,1,0,1,0,0,1,0

In [9]:
df = df.loc[:,~df.columns.duplicated()]
df

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,No,0,No,5849,0.0,NaN,360.0,1.0,Y,0,1,1,0,0,0,1
1,Yes,1,No,4583,1508.0,128.0,360.0,1.0,N,0,1,1,0,1,0,0
2,Yes,0,Yes,3000,0.0,66.0,360.0,1.0,Y,0,1,1,0,0,0,1
3,Yes,0,No,2583,2358.0,120.0,360.0,1.0,Y,0,1,0,1,0,0,1
4,No,0,No,6000,0.0,141.0,360.0,1.0,Y,0,1,1,0,0,0,1
5,Yes,2,Yes,5417,4196.0,267.0,360.0,1.0,Y,0,1,1,0,0,0,1
6,Yes,0,No,2333,1516.0,95.0,360.0,1.0,Y,0,1,0,1,0,0,1
7,Yes,3+,No,3036,2504.0,158.0,360.0,0.0,N,0,1,1,0,0,1,0
8,Yes,2,No,4006,1526.0,168.0,360.0,1.0,Y,0,1,1,0,0,0,1
9,Yes,1,No,12841,10968.0,349.0,360.0,1.0,N,0,1,1,0,0,1,0
10,Yes,2,No,3200,700.0,70.0,360.0,1.0,Y,0,1,1,0,0,0,1
11,Yes,2,NaN,2500,1840.0,109.0,360.0,1.0,Y,0,1,1,0,0,0,1
12,Yes,2,No,3073,8106.0,200.0,360.0,1.0,Y,0,1,1,0,0,0,1
13,No,0,No,1853,2840.0,114.0,360.0,1.0,N,0,1,1,0,1,0,0
14,Yes,2,No,1299,1086.0,17.0,120.0,1.0,Y,0,1,1,0,0,0,1
15,No,0,No,4950,0.0,125.0,360.0,1.0,Y,0,1,1,0,0,0,1
16,No,1,No,3596,0.0,100.0,240.0,NaN,Y,0,1,0,1,0,0,1
17,No,0,No,3510,0.0,76.0,360.0,0.0,N,1,0,1,0,0,0,1
18,Yes,0,No,4887,0.0,133.0,360.0,1.0,N,0,1,0,1,1,0,0
19,Yes,0,NaN,2600,3500.0,115.0,NaN,1.0,Y,0,1,1,0,0,0,1
20,Yes,0,No,7660,0.0,104.0,360.0,0.0,N,0,1,0,1,0,0,1
21,Yes,1,No,5955,5625.0,315.0,360.0,1.0,Y,0,1,1,0,0,0,1
22,Yes,0,No,2600,1911.0,116.0,360.0,0.0,N,0,1,0,1,0,1,0
23,Yes,2,No,3365,1917.0,112.0,360.0,0.0,N,0,0,0,1,1,0,0
24,Yes,1,NaN,3717,2925.0,151.0,360.0,NaN,N,0,1,1,0,0,1,0
25,Yes,0,Yes,9560,0.0,191.0,360.0,1.0,Y,0,1,1,0,0,1,0
26,Yes,0,No,2799,2253.0,122.0,360.0,1.0,Y,0,1,1,0,0,1,0
27,Yes,2,No,4226,1040.0,110.0,360.0,1.0,Y,0,1,0,1,0,0,1
28,No,0,No,1442,0.0,35.0,360.0,1.0,N,0,1,0,1,0,0,1
29,No,2,NaN,3750,2083.0,120.0,360.0,1.0,Y,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,Yes,1,No,2787,1917.0,146.0,360.0,0.0,N,0,1,1,0,1,0,0
585,Yes,1,No,4283,3000.0,172.0,84.0,1.0,N,0,1,1,0,1,0,0
586,Yes,0,No,2297,1522.0,104.0,360.0,1.0,Y,0,1,1,0,0,0,1
587,No,0,No,2165,0.0,70.0,360.0,1.0,Y,1,0,0,1,0,1,0
588,No,0,No,4750,0.0,94.0,360.0,1.0,Y,0,0,1,0,0,1,0
589,Yes,2,Yes,2726,0.0,106.0,360.0,0.0,N,0,1,1,0,0,1,0
590,Yes,0,No,3000,3416.0,56.0,180.0,1.0,Y,0,1,1,0,0,1,0
591,Yes,2,Yes,6000,0.0,205.0,240.0,1.0,N,0,1,1,0,0,1,0
592,No,3+,Yes,9357,0.0,292.0,360.0,1.0,Y,0,0,1,0,0,1,0
593,Yes,0,No,3859,3300.0,142.0,180.0,1.0,Y,0,1,1,0,1,0,0
594,Yes,0,Yes,16120,0.0,260.0,360.0,1.0,Y,0,1,1,0,0,0,1
595,No,0,No,3833,0.0,110.0,360.0,1.0,Y,0,1,0,1,1,0,0
596,Yes,2,Yes,6383,1000.0,187.0,360.0,1.0,N,0,1,0,1,1,0,0
597,No,NaN,No,2987,0.0,88.0,360.0,0.0,N,0,1,1,0,0,1,0
598,Yes,0,Yes,9963,0.0,180.0,360.0,1.0,Y,0,1,1,0,1,0,0
599,Yes,2,No,5780,0.0,192.0,360.0,1.0,Y,0,1,1,0,0,0,1
600,No,3+,NaN,416,41667.0,350.0,180.0,NaN,N,1,0,1,0,0,0,1
601,Yes,0,NaN,2894,2792.0,155.0,360.0,1.0,Y,0,1,0,1,1,0,0
602,Yes,3+,No,5703,0.0,128.0,360.0,1.0,Y,0,1,1,0,0,0,1
603,No,0,No,3676,4301.0,172.0,360.0,1.0,Y,0,1,1,0,1,0,0
604,Yes,1,No,12000,0.0,496.0,360.0,1.0,Y,1,0,1,0,0,1,0
605,Yes,0,No,2400,3800.0,NaN,180.0,1.0,N,0,1,0,1,0,0,1
606,Yes,1,No,3400,2500.0,173.0,360.0,1.0,Y,0,1,1,0,0,1,0
607,Yes,2,No,3987,1411.0,157.0,360.0,1.0,Y,0,1,0,1,1,0,0
608,Yes,0,No,3232,1950.0,108.0,360.0,1.0,Y,0,1,1,0,1,0,0
609,No,0,No,2900,0.0,71.0,360.0,1.0,Y,1,0,1,0,1,0,0
610,Yes,3+,No,4106,0.0,40.0,180.0,1.0,Y,0,1,1,0,1,0,0
611,Yes,1,No,8072,240.0,253.0,360.0,1.0,Y,0,1,1,0,0,0,1
612,Yes,2,No,7583,0.0,187.0,360.0,1.0,Y,0,1,1,0,0,0,1
613,No,0,Yes,4583,0.0,133.0,360.0,0.0,N,1,0,1,0,0,1,0

In [10]:
df['Married']=df['Married'].replace({'Yes':1,'No':0})
df

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,No,5849,0.0,NaN,360.0,1.0,Y,0,1,1,0,0,0,1
1,1.0,1,No,4583,1508.0,128.0,360.0,1.0,N,0,1,1,0,1,0,0
2,1.0,0,Yes,3000,0.0,66.0,360.0,1.0,Y,0,1,1,0,0,0,1
3,1.0,0,No,2583,2358.0,120.0,360.0,1.0,Y,0,1,0,1,0,0,1
4,0.0,0,No,6000,0.0,141.0,360.0,1.0,Y,0,1,1,0,0,0,1
5,1.0,2,Yes,5417,4196.0,267.0,360.0,1.0,Y,0,1,1,0,0,0,1
6,1.0,0,No,2333,1516.0,95.0,360.0,1.0,Y,0,1,0,1,0,0,1
7,1.0,3+,No,3036,2504.0,158.0,360.0,0.0,N,0,1,1,0,0,1,0
8,1.0,2,No,4006,1526.0,168.0,360.0,1.0,Y,0,1,1,0,0,0,1
9,1.0,1,No,12841,10968.0,349.0,360.0,1.0,N,0,1,1,0,0,1,0
10,1.0,2,No,3200,700.0,70.0,360.0,1.0,Y,0,1,1,0,0,0,1
11,1.0,2,NaN,2500,1840.0,109.0,360.0,1.0,Y,0,1,1,0,0,0,1
12,1.0,2,No,3073,8106.0,200.0,360.0,1.0,Y,0,1,1,0,0,0,1
13,0.0,0,No,1853,2840.0,114.0,360.0,1.0,N,0,1,1,0,1,0,0
14,1.0,2,No,1299,1086.0,17.0,120.0,1.0,Y,0,1,1,0,0,0,1
15,0.0,0,No,4950,0.0,125.0,360.0,1.0,Y,0,1,1,0,0,0,1
16,0.0,1,No,3596,0.0,100.0,240.0,NaN,Y,0,1,0,1,0,0,1
17,0.0,0,No,3510,0.0,76.0,360.0,0.0,N,1,0,1,0,0,0,1
18,1.0,0,No,4887,0.0,133.0,360.0,1.0,N,0,1,0,1,1,0,0
19,1.0,0,NaN,2600,3500.0,115.0,NaN,1.0,Y,0,1,1,0,0,0,1
20,1.0,0,No,7660,0.0,104.0,360.0,0.0,N,0,1,0,1,0,0,1
21,1.0,1,No,5955,5625.0,315.0,360.0,1.0,Y,0,1,1,0,0,0,1
22,1.0,0,No,2600,1911.0,116.0,360.0,0.0,N,0,1,0,1,0,1,0
23,1.0,2,No,3365,1917.0,112.0,360.0,0.0,N,0,0,0,1,1,0,0
24,1.0,1,NaN,3717,2925.0,151.0,360.0,NaN,N,0,1,1,0,0,1,0
25,1.0,0,Yes,9560,0.0,191.0,360.0,1.0,Y,0,1,1,0,0,1,0
26,1.0,0,No,2799,2253.0,122.0,360.0,1.0,Y,0,1,1,0,0,1,0
27,1.0,2,No,4226,1040.0,110.0,360.0,1.0,Y,0,1,0,1,0,0,1
28,0.0,0,No,1442,0.0,35.0,360.0,1.0,N,0,1,0,1,0,0,1
29,0.0,2,NaN,3750,2083.0,120.0,360.0,1.0,Y,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,No,2787,1917.0,146.0,360.0,0.0,N,0,1,1,0,1,0,0
585,1.0,1,No,4283,3000.0,172.0,84.0,1.0,N,0,1,1,0,1,0,0
586,1.0,0,No,2297,1522.0,104.0,360.0,1.0,Y,0,1,1,0,0,0,1
587,0.0,0,No,2165,0.0,70.0,360.0,1.0,Y,1,0,0,1,0,1,0
588,0.0,0,No,4750,0.0,94.0,360.0,1.0,Y,0,0,1,0,0,1,0
589,1.0,2,Yes,2726,0.0,106.0,360.0,0.0,N,0,1,1,0,0,1,0
590,1.0,0,No,3000,3416.0,56.0,180.0,1.0,Y,0,1,1,0,0,1,0
591,1.0,2,Yes,6000,0.0,205.0,240.0,1.0,N,0,1,1,0,0,1,0
592,0.0,3+,Yes,9357,0.0,292.0,360.0,1.0,Y,0,0,1,0,0,1,0
593,1.0,0,No,3859,3300.0,142.0,180.0,1.0,Y,0,1,1,0,1,0,0
594,1.0,0,Yes,16120,0.0,260.0,360.0,1.0,Y,0,1,1,0,0,0,1
595,0.0,0,No,3833,0.0,110.0,360.0,1.0,Y,0,1,0,1,1,0,0
596,1.0,2,Yes,6383,1000.0,187.0,360.0,1.0,N,0,1,0,1,1,0,0
597,0.0,NaN,No,2987,0.0,88.0,360.0,0.0,N,0,1,1,0,0,1,0
598,1.0,0,Yes,9963,0.0,180.0,360.0,1.0,Y,0,1,1,0,1,0,0
599,1.0,2,No,5780,0.0,192.0,360.0,1.0,Y,0,1,1,0,0,0,1
600,0.0,3+,NaN,416,41667.0,350.0,180.0,NaN,N,1,0,1,0,0,0,1
601,1.0,0,NaN,2894,2792.0,155.0,360.0,1.0,Y,0,1,0,1,1,0,0
602,1.0,3+,No,5703,0.0,128.0,360.0,1.0,Y,0,1,1,0,0,0,1
603,0.0,0,No,3676,4301.0,172.0,360.0,1.0,Y,0,1,1,0,1,0,0
604,1.0,1,No,12000,0.0,496.0,360.0,1.0,Y,1,0,1,0,0,1,0
605,1.0,0,No,2400,3800.0,NaN,180.0,1.0,N,0,1,0,1,0,0,1
606,1.0,1,No,3400,2500.0,173.0,360.0,1.0,Y,0,1,1,0,0,1,0
607,1.0,2,No,3987,1411.0,157.0,360.0,1.0,Y,0,1,0,1,1,0,0
608,1.0,0,No,3232,1950.0,108.0,360.0,1.0,Y,0,1,1,0,1,0,0
609,0.0,0,No,2900,0.0,71.0,360.0,1.0,Y,1,0,1,0,1,0,0
610,1.0,3+,No,4106,0.0,40.0,180.0,1.0,Y,0,1,1,0,1,0,0
611,1.0,1,No,8072,240.0,253.0,360.0,1.0,Y,0,1,1,0,0,0,1
612,1.0,2,No,7583,0.0,187.0,360.0,1.0,Y,0,1,1,0,0,0,1
613,0.0,0,Yes,4583,0.0,133.0,360.0,0.0,N,1,0,1,0,0,1,0

In [11]:
df['Self_Employed']=df['Self_Employed'].replace({'Yes':1,'No':0})
df

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,NaN,360.0,1.0,Y,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,N,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,Y,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,Y,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,Y,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,Y,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,Y,0,1,0,1,0,0,1
7,1.0,3+,0.0,3036,2504.0,158.0,360.0,0.0,N,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,Y,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,N,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,Y,0,1,1,0,0,0,1
11,1.0,2,NaN,2500,1840.0,109.0,360.0,1.0,Y,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,Y,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,N,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,Y,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,Y,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,NaN,Y,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,N,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,N,0,1,0,1,1,0,0
19,1.0,0,NaN,2600,3500.0,115.0,NaN,1.0,Y,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,N,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,Y,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,N,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,N,0,0,0,1,1,0,0
24,1.0,1,NaN,3717,2925.0,151.0,360.0,NaN,N,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,Y,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,Y,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,Y,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,N,0,1,0,1,0,0,1
29,0.0,2,NaN,3750,2083.0,120.0,360.0,1.0,Y,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,N,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,N,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,Y,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,Y,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,Y,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,N,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,Y,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,N,0,1,1,0,0,1,0
592,0.0,3+,1.0,9357,0.0,292.0,360.0,1.0,Y,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,Y,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,Y,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,Y,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,N,0,1,0,1,1,0,0
597,0.0,NaN,0.0,2987,0.0,88.0,360.0,0.0,N,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,Y,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,Y,0,1,1,0,0,0,1
600,0.0,3+,NaN,416,41667.0,350.0,180.0,NaN,N,1,0,1,0,0,0,1
601,1.0,0,NaN,2894,2792.0,155.0,360.0,1.0,Y,0,1,0,1,1,0,0
602,1.0,3+,0.0,5703,0.0,128.0,360.0,1.0,Y,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,Y,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,Y,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,NaN,180.0,1.0,N,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,Y,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,Y,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,Y,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,Y,1,0,1,0,1,0,0
610,1.0,3+,0.0,4106,0.0,40.0,180.0,1.0,Y,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,Y,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,Y,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,N,1,0,1,0,0,1,0

In [12]:
df['Loan_Status'] = df['Loan_Status'].replace({'Y': 1, 'N': 0})
df

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,NaN,360.0,1.0,1,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,1,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,1,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,1,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,1,0,1,0,1,0,0,1
7,1.0,3+,0.0,3036,2504.0,158.0,360.0,0.0,0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,1,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,1,0,1,1,0,0,0,1
11,1.0,2,NaN,2500,1840.0,109.0,360.0,1.0,1,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,1,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,1,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,1,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,NaN,1,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,0,1,0,1,1,0,0
19,1.0,0,NaN,2600,3500.0,115.0,NaN,1.0,1,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,1,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,0,1,1,0,0
24,1.0,1,NaN,3717,2925.0,151.0,360.0,NaN,0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,1,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,1,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,1,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,0,1,0,1,0,0,1
29,0.0,2,NaN,3750,2083.0,120.0,360.0,1.0,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,1,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,1,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,1,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,0,1,1,0,0,1,0
592,0.0,3+,1.0,9357,0.0,292.0,360.0,1.0,1,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,1,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,1,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,1,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,0,1,0,1,1,0,0
597,0.0,NaN,0.0,2987,0.0,88.0,360.0,0.0,0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,1,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,1,0,1,1,0,0,0,1
600,0.0,3+,NaN,416,41667.0,350.0,180.0,NaN,0,1,0,1,0,0,0,1
601,1.0,0,NaN,2894,2792.0,155.0,360.0,1.0,1,0,1,0,1,1,0,0
602,1.0,3+,0.0,5703,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,1,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,NaN,180.0,1.0,0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,1,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,1,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,1,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,1,0,1,0,1,0,0
610,1.0,3+,0.0,4106,0.0,40.0,180.0,1.0,1,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,1,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,0,1,0,1,0,0,1,0

In [13]:
df['Dependents'] = df['Dependents'].replace({'3+':'3'})
df

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,NaN,360.0,1.0,1,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,1,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,1,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,1,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,1,0,1,0,1,0,0,1
7,1.0,3,0.0,3036,2504.0,158.0,360.0,0.0,0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,1,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,1,0,1,1,0,0,0,1
11,1.0,2,NaN,2500,1840.0,109.0,360.0,1.0,1,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,1,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,1,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,1,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,NaN,1,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,0,1,0,1,1,0,0
19,1.0,0,NaN,2600,3500.0,115.0,NaN,1.0,1,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,1,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,0,1,1,0,0
24,1.0,1,NaN,3717,2925.0,151.0,360.0,NaN,0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,1,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,1,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,1,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,0,1,0,1,0,0,1
29,0.0,2,NaN,3750,2083.0,120.0,360.0,1.0,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,1,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,1,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,1,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,0,1,1,0,0,1,0
592,0.0,3,1.0,9357,0.0,292.0,360.0,1.0,1,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,1,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,1,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,1,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,0,1,0,1,1,0,0
597,0.0,NaN,0.0,2987,0.0,88.0,360.0,0.0,0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,1,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,1,0,1,1,0,0,0,1
600,0.0,3,NaN,416,41667.0,350.0,180.0,NaN,0,1,0,1,0,0,0,1
601,1.0,0,NaN,2894,2792.0,155.0,360.0,1.0,1,0,1,0,1,1,0,0
602,1.0,3,0.0,5703,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,1,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,NaN,180.0,1.0,0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,1,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,1,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,1,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,1,0,1,0,1,0,0
610,1.0,3,0.0,4106,0.0,40.0,180.0,1.0,1,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,1,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,0,1,0,1,0,0,1,0

# filling missing values

In [14]:
df.isnull().sum()

Married                     3
Dependents                 15
Self_Employed              32
ApplicantIncome             0
CoapplicantIncome           0
LoanAmount                 22
Loan_Amount_Term           14
Credit_History             50
Loan_Status                 0
gender_Female               0
gender_Male                 0
education_Graduate          0
education_Not Graduate      0
property_area_Rural         0
property_area_Semiurban     0
property_area_Urban         0
dtype: int64

In [15]:
median = df['Married'].median()
median

1.0

In [16]:
df['Married'].fillna(median, inplace=True)
df

C:\Users\hp\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,NaN,360.0,1.0,1,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,1,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,1,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,1,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,1,0,1,0,1,0,0,1
7,1.0,3,0.0,3036,2504.0,158.0,360.0,0.0,0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,1,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,1,0,1,1,0,0,0,1
11,1.0,2,NaN,2500,1840.0,109.0,360.0,1.0,1,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,1,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,1,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,1,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,NaN,1,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,0,1,0,1,1,0,0
19,1.0,0,NaN,2600,3500.0,115.0,NaN,1.0,1,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,1,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,0,1,1,0,0
24,1.0,1,NaN,3717,2925.0,151.0,360.0,NaN,0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,1,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,1,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,1,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,0,1,0,1,0,0,1
29,0.0,2,NaN,3750,2083.0,120.0,360.0,1.0,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,1,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,1,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,1,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,0,1,1,0,0,1,0
592,0.0,3,1.0,9357,0.0,292.0,360.0,1.0,1,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,1,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,1,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,1,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,0,1,0,1,1,0,0
597,0.0,NaN,0.0,2987,0.0,88.0,360.0,0.0,0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,1,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,1,0,1,1,0,0,0,1
600,0.0,3,NaN,416,41667.0,350.0,180.0,NaN,0,1,0,1,0,0,0,1
601,1.0,0,NaN,2894,2792.0,155.0,360.0,1.0,1,0,1,0,1,1,0,0
602,1.0,3,0.0,5703,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,1,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,NaN,180.0,1.0,0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,1,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,1,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,1,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,1,0,1,0,1,0,0
610,1.0,3,0.0,4106,0.0,40.0,180.0,1.0,1,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,1,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,0,1,0,1,0,0,1,0

In [17]:
df.isnull().sum()

Married                     0
Dependents                 15
Self_Employed              32
ApplicantIncome             0
CoapplicantIncome           0
LoanAmount                 22
Loan_Amount_Term           14
Credit_History             50
Loan_Status                 0
gender_Female               0
gender_Male                 0
education_Graduate          0
education_Not Graduate      0
property_area_Rural         0
property_area_Semiurban     0
property_area_Urban         0
dtype: int64

In [18]:
median1 = df['Dependents'].median()
median2 = df['Self_Employed'].median()
median3 = df['LoanAmount'].median()
median4 = df['Loan_Amount_Term'].median()
median5 = df['Credit_History'].median()

In [19]:
df['Dependents'].fillna(median1,inplace=True)
df['Self_Employed'].fillna(median2,inplace=True)
df['LoanAmount'].fillna(median3,inplace=True)
df['Loan_Amount_Term'].fillna(median4,inplace=True)
df['Credit_History'].fillna(median5,inplace=True)
df

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,1,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,1,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,1,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,1,0,1,0,1,0,0,1
7,1.0,3,0.0,3036,2504.0,158.0,360.0,0.0,0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,1,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,1,0,1,1,0,0,0,1
11,1.0,2,0.0,2500,1840.0,109.0,360.0,1.0,1,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,1,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,1,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,1,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,1.0,1,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,0,1,0,1,1,0,0
19,1.0,0,0.0,2600,3500.0,115.0,360.0,1.0,1,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,1,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,0,1,1,0,0
24,1.0,1,0.0,3717,2925.0,151.0,360.0,1.0,0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,1,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,1,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,1,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,0,1,0,1,0,0,1
29,0.0,2,0.0,3750,2083.0,120.0,360.0,1.0,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,1,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,1,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,1,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,0,1,1,0,0,1,0
592,0.0,3,1.0,9357,0.0,292.0,360.0,1.0,1,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,1,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,1,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,1,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,0,1,0,1,1,0,0
597,0.0,0,0.0,2987,0.0,88.0,360.0,0.0,0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,1,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,1,0,1,1,0,0,0,1
600,0.0,3,0.0,416,41667.0,350.0,180.0,1.0,0,1,0,1,0,0,0,1
601,1.0,0,0.0,2894,2792.0,155.0,360.0,1.0,1,0,1,0,1,1,0,0
602,1.0,3,0.0,5703,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,1,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,128.0,180.0,1.0,0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,1,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,1,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,1,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,1,0,1,0,1,0,0
610,1.0,3,0.0,4106,0.0,40.0,180.0,1.0,1,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,1,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,0,1,0,1,0,0,1,0

In [20]:
df.isnull().sum()

Married                    0
Dependents                 0
Self_Employed              0
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                 0
Loan_Amount_Term           0
Credit_History             0
Loan_Status                0
gender_Female              0
gender_Male                0
education_Graduate         0
education_Not Graduate     0
property_area_Rural        0
property_area_Semiurban    0
property_area_Urban        0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 16 columns):
Married                    614 non-null float64
Dependents                 614 non-null object
Self_Employed              614 non-null float64
ApplicantIncome            614 non-null int64
CoapplicantIncome          614 non-null float64
LoanAmount                 614 non-null float64
Loan_Amount_Term           614 non-null float64
Credit_History             614 non-null float64
Loan_Status                614 non-null int64
gender_Female              614 non-null uint8
gender_Male                614 non-null uint8
education_Graduate         614 non-null uint8
education_Not Graduate     614 non-null uint8
property_area_Rural        614 non-null uint8
property_area_Semiurban    614 non-null uint8
property_area_Urban        614 non-null uint8
dtypes: float64(6), int64(2), object(1), uint8(7)
memory usage: 47.4+ KB

In [22]:
df['Dependents'].values

array(['0', '1', '0', '0', '0', '2', '0', '3', '2', '1', '2', '2', '2',
       '0', '2', '0', '1', '0', '0', '0', '0', '1', '0', '2', '1', '0',
       '0', '2', '0', '2', '1', '0', '1', '0', '3', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0',
       '0', '2', '1', '2', '0', '0', '1', '2', '0', '3', '0', '1', '0',
       '0', '0', '1', '3', '0', '0', '2', '0', '3', '3', '0', '0', '1',
       '3', '3', '0', '1', '2', '0', '1', '0', '2', '0', '0', '0', '0',
       '2', '2', '0', '0', '0', '0', '0', '0', '0', '2', '0', 0.0, '0',
       0.0, '1', '2', '0', '2', '3', '0', '0', '0', '1', '0', '1', '0',
       '1', '0', '0', 0.0, '0', '0', '2', '0', '0', '3', '0', '1', '0',
       '0', '0', '0', '0', '0', '3', '0', '2', '0', '2', '2', '0', '0',
       '0', '2', '0', '2', '1', '0', '0', '0', '0', '0', '2', '0', '3',
       '1', '1', '0', '0', '0', '0', '1', '2', '0', '0', '0', '0', '0',
       '2', '0', '3', '3', '0', '0', '0', '2', '3', '1', '0', '1', '0',
       '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '1', '2', '3', '1', '2', '0', '0', '0',
       '0', '0', '0', '3', '1', '3', '0', '3', '0', '0', '2', '2', '0',
       '2', '0', '0', '0', '0', 0.0, '2', 0.0, '0', '1', '0', '0', '0',
       '1', '1', '0', '0', '1', '1', '2', '1', '0', '2', '0', '0', '2',
       '1', '1', '0', '0', '2', '0', '1', '0', '3', '0', '3', '0', '3',
       '1', '0', '1', '0', '0', '0', '2', '3', '0', '1', '0', '0', '0',
       '0', '2', '1', '0', '0', '0', '0', '1', '0', '2', '0', '0', '0',
       '0', '0', '0', '0', '0', '2', '2', 0.0, '0', '3', '1', '1', '0',
       '1', '0', 0.0, '0', '1', '0', '0', '0', '0', '0', '2', '0', '0',
       '0', '2', '0', '1', '2', '0', '1', '1', '0', '3', '2', '0', '3',
       '1', '0', '0', '0', '0', '1', '0', 0.0, '0', '1', 0.0, '1', '2',
       '3', '0', '3', '0', '1', '3', '2', '0', 0.0, '2', '0', '0', '0',
       '0', '3', '0', '0', 0.0, '2', '1', '0', '3', '1', '2', '0', '0',
       '0', '0', '0', '0', '1', '0', '0', '2', '2', '1', '0', '0', '3',
       '0', '0', '2', '0', '0', '0', '0', '2', '1', '0', '0', '0', '0',
       '3', '3', '0', '2', '2', '2', '0', '0', '0', '0', '2', '0', '0',
       '0', '0', '0', '0', '0', '1', '3', '1', '0', '0', '0', '0', '0',
       '1', '2', '0', '0', '0', '0', '0', '1', '0', '0', '1', '2', '0',
       '0', '1', '0', '0', '0', '0', 0.0, '0', '0', '0', '0', '0', '0',
       '3', '1', '0', '1', '2', '0', '2', '1', '2', '2', '0', '0', '0',
       '2', '0', '0', '2', '0', '0', '3', '0', '1', '0', '0', '3', '0',
       '2', '0', '1', '1', '3', '0', '2', '2', '2', '2', '1', '2', '0',
       '3', '0', '0', '2', '1', '2', '1', '2', '0', '0', '1', '0', '0',
       '0', '1', '0', '0', '1', '0', '0', '0', '2', '1', '0', '2', '0',
       '0', '0', '1', '0', '1', '2', '0', '0', '3', '2', 0.0, '0', '0',
       '2', '0', '3', '2', '0', '2', '0', '1', '1', '0', '0', '3', '2',
       '1', '0', '0', '0', '2', '0', '3', '1', '0', '1', '1', '0', '0',
       '0', '0', '0', '0', '2', '1', '1', '0', '0', '1', '0', '3', '0',
       '0', '2', '1', '0', '0', '2', '0', '0', '3', '0', '0', '1', 0.0,
       '2', '2', '3', '2', '0', '0', '1', '0', '2', '0', '0', '1', '1',
       '1', '0', '0', '0', '2', '0', '2', '3', '0', '0', '0', '2', 0.0,
       '0', '2', '3', '0', '3', '0', '1', '0', '1', '2', '0', '0', '3',
       '1', '2', '0'], dtype=object)

In [23]:
df['Dependents']=df['Dependents'].astype(int)
df

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,1,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,1,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,1,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,1,0,1,0,1,0,0,1
7,1.0,3,0.0,3036,2504.0,158.0,360.0,0.0,0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,1,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,1,0,1,1,0,0,0,1
11,1.0,2,0.0,2500,1840.0,109.0,360.0,1.0,1,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,1,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,1,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,1,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,1.0,1,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,0,1,0,1,1,0,0
19,1.0,0,0.0,2600,3500.0,115.0,360.0,1.0,1,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,1,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,0,1,1,0,0
24,1.0,1,0.0,3717,2925.0,151.0,360.0,1.0,0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,1,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,1,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,1,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,0,1,0,1,0,0,1
29,0.0,2,0.0,3750,2083.0,120.0,360.0,1.0,1,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,1,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,1,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,1,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,0,1,1,0,0,1,0
592,0.0,3,1.0,9357,0.0,292.0,360.0,1.0,1,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,1,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,1,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,1,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,0,1,0,1,1,0,0
597,0.0,0,0.0,2987,0.0,88.0,360.0,0.0,0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,1,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,1,0,1,1,0,0,0,1
600,0.0,3,0.0,416,41667.0,350.0,180.0,1.0,0,1,0,1,0,0,0,1
601,1.0,0,0.0,2894,2792.0,155.0,360.0,1.0,1,0,1,0,1,1,0,0
602,1.0,3,0.0,5703,0.0,128.0,360.0,1.0,1,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,1,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,128.0,180.0,1.0,0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,1,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,1,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,1,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,1,0,1,0,1,0,0
610,1.0,3,0.0,4106,0.0,40.0,180.0,1.0,1,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,1,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,1,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,0,1,0,1,0,0,1,0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 16 columns):
Married                    614 non-null float64
Dependents                 614 non-null int32
Self_Employed              614 non-null float64
ApplicantIncome            614 non-null int64
CoapplicantIncome          614 non-null float64
LoanAmount                 614 non-null float64
Loan_Amount_Term           614 non-null float64
Credit_History             614 non-null float64
Loan_Status                614 non-null int64
gender_Female              614 non-null uint8
gender_Male                614 non-null uint8
education_Graduate         614 non-null uint8
education_Not Graduate     614 non-null uint8
property_area_Rural        614 non-null uint8
property_area_Semiurban    614 non-null uint8
property_area_Urban        614 non-null uint8
dtypes: float64(6), int32(1), int64(2), uint8(7)
memory usage: 45.0 KB

# training the data

# logistic regression

In [25]:
X=df.iloc[:,[0,1,2,3,4,5,6,7,9,10,11,12,13,14,15]]
X

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
0,0.0,0,0.0,5849,0.0,128.0,360.0,1.0,0,1,1,0,0,0,1
1,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,1,1,0,1,0,0
2,1.0,0,1.0,3000,0.0,66.0,360.0,1.0,0,1,1,0,0,0,1
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,0,1,0,1,0,0,1
4,0.0,0,0.0,6000,0.0,141.0,360.0,1.0,0,1,1,0,0,0,1
5,1.0,2,1.0,5417,4196.0,267.0,360.0,1.0,0,1,1,0,0,0,1
6,1.0,0,0.0,2333,1516.0,95.0,360.0,1.0,0,1,0,1,0,0,1
7,1.0,3,0.0,3036,2504.0,158.0,360.0,0.0,0,1,1,0,0,1,0
8,1.0,2,0.0,4006,1526.0,168.0,360.0,1.0,0,1,1,0,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,1,1,0,0,1,0
10,1.0,2,0.0,3200,700.0,70.0,360.0,1.0,0,1,1,0,0,0,1
11,1.0,2,0.0,2500,1840.0,109.0,360.0,1.0,0,1,1,0,0,0,1
12,1.0,2,0.0,3073,8106.0,200.0,360.0,1.0,0,1,1,0,0,0,1
13,0.0,0,0.0,1853,2840.0,114.0,360.0,1.0,0,1,1,0,1,0,0
14,1.0,2,0.0,1299,1086.0,17.0,120.0,1.0,0,1,1,0,0,0,1
15,0.0,0,0.0,4950,0.0,125.0,360.0,1.0,0,1,1,0,0,0,1
16,0.0,1,0.0,3596,0.0,100.0,240.0,1.0,0,1,0,1,0,0,1
17,0.0,0,0.0,3510,0.0,76.0,360.0,0.0,1,0,1,0,0,0,1
18,1.0,0,0.0,4887,0.0,133.0,360.0,1.0,0,1,0,1,1,0,0
19,1.0,0,0.0,2600,3500.0,115.0,360.0,1.0,0,1,1,0,0,0,1
20,1.0,0,0.0,7660,0.0,104.0,360.0,0.0,0,1,0,1,0,0,1
21,1.0,1,0.0,5955,5625.0,315.0,360.0,1.0,0,1,1,0,0,0,1
22,1.0,0,0.0,2600,1911.0,116.0,360.0,0.0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,1,1,0,0
24,1.0,1,0.0,3717,2925.0,151.0,360.0,1.0,0,1,1,0,0,1,0
25,1.0,0,1.0,9560,0.0,191.0,360.0,1.0,0,1,1,0,0,1,0
26,1.0,0,0.0,2799,2253.0,122.0,360.0,1.0,0,1,1,0,0,1,0
27,1.0,2,0.0,4226,1040.0,110.0,360.0,1.0,0,1,0,1,0,0,1
28,0.0,0,0.0,1442,0.0,35.0,360.0,1.0,0,1,0,1,0,0,1
29,0.0,2,0.0,3750,2083.0,120.0,360.0,1.0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,1.0,1,0.0,2787,1917.0,146.0,360.0,0.0,0,1,1,0,1,0,0
585,1.0,1,0.0,4283,3000.0,172.0,84.0,1.0,0,1,1,0,1,0,0
586,1.0,0,0.0,2297,1522.0,104.0,360.0,1.0,0,1,1,0,0,0,1
587,0.0,0,0.0,2165,0.0,70.0,360.0,1.0,1,0,0,1,0,1,0
588,0.0,0,0.0,4750,0.0,94.0,360.0,1.0,0,0,1,0,0,1,0
589,1.0,2,1.0,2726,0.0,106.0,360.0,0.0,0,1,1,0,0,1,0
590,1.0,0,0.0,3000,3416.0,56.0,180.0,1.0,0,1,1,0,0,1,0
591,1.0,2,1.0,6000,0.0,205.0,240.0,1.0,0,1,1,0,0,1,0
592,0.0,3,1.0,9357,0.0,292.0,360.0,1.0,0,0,1,0,0,1,0
593,1.0,0,0.0,3859,3300.0,142.0,180.0,1.0,0,1,1,0,1,0,0
594,1.0,0,1.0,16120,0.0,260.0,360.0,1.0,0,1,1,0,0,0,1
595,0.0,0,0.0,3833,0.0,110.0,360.0,1.0,0,1,0,1,1,0,0
596,1.0,2,1.0,6383,1000.0,187.0,360.0,1.0,0,1,0,1,1,0,0
597,0.0,0,0.0,2987,0.0,88.0,360.0,0.0,0,1,1,0,0,1,0
598,1.0,0,1.0,9963,0.0,180.0,360.0,1.0,0,1,1,0,1,0,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,0,1,1,0,0,0,1
600,0.0,3,0.0,416,41667.0,350.0,180.0,1.0,1,0,1,0,0,0,1
601,1.0,0,0.0,2894,2792.0,155.0,360.0,1.0,0,1,0,1,1,0,0
602,1.0,3,0.0,5703,0.0,128.0,360.0,1.0,0,1,1,0,0,0,1
603,0.0,0,0.0,3676,4301.0,172.0,360.0,1.0,0,1,1,0,1,0,0
604,1.0,1,0.0,12000,0.0,496.0,360.0,1.0,1,0,1,0,0,1,0
605,1.0,0,0.0,2400,3800.0,128.0,180.0,1.0,0,1,0,1,0,0,1
606,1.0,1,0.0,3400,2500.0,173.0,360.0,1.0,0,1,1,0,0,1,0
607,1.0,2,0.0,3987,1411.0,157.0,360.0,1.0,0,1,0,1,1,0,0
608,1.0,0,0.0,3232,1950.0,108.0,360.0,1.0,0,1,1,0,1,0,0
609,0.0,0,0.0,2900,0.0,71.0,360.0,1.0,1,0,1,0,1,0,0
610,1.0,3,0.0,4106,0.0,40.0,180.0,1.0,0,1,1,0,1,0,0
611,1.0,1,0.0,8072,240.0,253.0,360.0,1.0,0,1,1,0,0,0,1
612,1.0,2,0.0,7583,0.0,187.0,360.0,1.0,0,1,1,0,0,0,1
613,0.0,0,1.0,4583,0.0,133.0,360.0,0.0,1,0,1,0,0,1,0

In [26]:
y=df.iloc[:,[8]]
y

     Loan_Status
0              1
1              0
2              1
3              1
4              1
5              1
6              1
7              0
8              1
9              0
10             1
11             1
12             1
13             0
14             1
15             1
16             1
17             0
18             0
19             1
20             0
21             1
22             0
23             0
24             0
25             1
26             1
27             1
28             0
29             1
..           ...
584            0
585            0
586            1
587            1
588            1
589            0
590            1
591            0
592            1
593            1
594            1
595            1
596            0
597            0
598            1
599            1
600            0
601            1
602            1
603            1
604            1
605            0
606            1
607            1
608            1
609            1
610            1
611            1
612            1
613            0

[614 rows x 1 columns]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=1)

In [29]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [30]:
model.fit(X_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
y_predicted=model.predict(X_test)

In [32]:
X_test

,Married,Dependents,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,gender_Female,gender_Male,education_Graduate,education_Not Graduate,property_area_Rural,property_area_Semiurban,property_area_Urban
533,0.0,1,0.0,11250,0.0,196.0,360.0,1.0,0,1,1,0,0,1,0
544,1.0,0,0.0,3017,663.0,102.0,360.0,1.0,1,0,0,1,0,1,0
41,0.0,0,0.0,1800,1213.0,47.0,360.0,1.0,0,1,1,0,0,0,1
148,0.0,0,0.0,10000,1666.0,225.0,360.0,1.0,1,0,1,0,1,0,0
111,1.0,0,0.0,2929,2333.0,139.0,360.0,1.0,1,0,1,0,0,1,0
293,0.0,0,0.0,5417,0.0,143.0,480.0,0.0,1,0,1,0,0,0,1
435,1.0,0,0.0,10047,0.0,128.0,240.0,1.0,1,0,1,0,0,1,0
407,0.0,0,0.0,2213,0.0,66.0,360.0,1.0,1,0,0,1,1,0,0
311,0.0,0,0.0,2927,2405.0,111.0,360.0,1.0,0,1,0,1,0,1,0
23,1.0,2,0.0,3365,1917.0,112.0,360.0,0.0,0,0,0,1,1,0,0
242,0.0,0,0.0,2965,5701.0,155.0,60.0,1.0,0,1,1,0,0,0,1
185,1.0,0,1.0,39147,4750.0,120.0,360.0,1.0,0,1,1,0,0,1,0
521,0.0,0,0.0,2500,0.0,55.0,360.0,1.0,0,1,1,0,0,1,0
496,1.0,0,0.0,2600,1700.0,107.0,360.0,1.0,0,1,0,1,1,0,0
566,0.0,0,0.0,3333,0.0,70.0,360.0,1.0,0,1,1,0,0,0,1
301,1.0,0,0.0,2875,1750.0,105.0,360.0,1.0,0,1,0,1,0,1,0
375,1.0,0,0.0,4817,923.0,120.0,180.0,1.0,0,1,1,0,0,0,1
200,1.0,1,0.0,2600,2500.0,90.0,360.0,1.0,0,1,0,1,0,1,0
599,1.0,2,0.0,5780,0.0,192.0,360.0,1.0,0,1,1,0,0,0,1
306,0.0,0,0.0,3762,1666.0,135.0,360.0,1.0,1,0,1,0,1,0,0
132,0.0,0,0.0,2718,0.0,70.0,360.0,1.0,0,1,1,0,0,1,0
559,1.0,0,0.0,4180,2306.0,182.0,360.0,1.0,1,0,1,0,0,1,0
0,0.0,0,0.0,5849,0.0,128.0,360.0,1.0,0,1,1,0,0,0,1
135,1.0,3,0.0,4000,7750.0,290.0,360.0,1.0,0,1,1,0,0,1,0
195,1.0,1,0.0,3125,2583.0,170.0,360.0,1.0,0,1,1,0,0,1,0
386,0.0,0,0.0,2346,1600.0,132.0,360.0,1.0,0,1,0,1,0,1,0
563,0.0,0,1.0,5800,0.0,132.0,360.0,1.0,0,1,0,1,0,1,0
201,0.0,2,0.0,4923,0.0,166.0,360.0,0.0,0,1,1,0,0,1,0
520,1.0,2,0.0,2192,1742.0,45.0,360.0,1.0,0,1,0,1,0,1,0
518,0.0,0,0.0,4683,1915.0,185.0,360.0,1.0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,1.0,0,0.0,7578,1010.0,175.0,360.0,1.0,0,1,1,0,0,1,0
574,1.0,3,0.0,6406,0.0,150.0,360.0,1.0,0,1,1,0,0,1,0
425,1.0,0,0.0,2666,4300.0,121.0,360.0,1.0,0,1,1,0,1,0,0
92,1.0,2,0.0,3273,1820.0,81.0,360.0,1.0,0,1,0,1,0,0,1
295,1.0,3,0.0,4416,1250.0,110.0,360.0,1.0,0,1,1,0,0,0,1
484,1.0,2,0.0,8333,0.0,246.0,360.0,1.0,0,1,1,0,0,1,0
260,1.0,1,0.0,6083,4250.0,330.0,360.0,1.0,0,1,1,0,0,0,1
268,0.0,0,0.0,3418,0.0,135.0,360.0,1.0,1,0,1,0,1,0,0
103,1.0,0,0.0,4652,3583.0,128.0,360.0,1.0,0,1,1,0,0,1,0
560,1.0,2,0.0,3675,242.0,108.0,360.0,1.0,0,1,0,1,0,1,0
224,1.0,0,0.0,6250,0.0,128.0,360.0,1.0,0,1,1,0,0,1,0
187,1.0,0,0.0,2383,2138.0,58.0,360.0,1.0,0,1,1,0,1,0,0
80,0.0,0,0.0,3846,0.0,111.0,360.0,1.0,1,0,1,0,0,1,0
516,1.0,2,0.0,2031,1632.0,113.0,480.0,1.0,1,0,1,0,0,1,0
379,1.0,2,0.0,5391,0.0,130.0,360.0,1.0,0,1,1,0,0,0,1
373,0.0,1,0.0,3062,1987.0,111.0,180.0,0.0,0,1,1,0,0,0,1
436,0.0,0,0.0,1926,1851.0,50.0,360.0,1.0,0,1,1,0,0,1,0
545,1.0,0,0.0,2768,1950.0,155.0,360.0,1.0,0,1,1,0,1,0,0
3,1.0,0,0.0,2583,2358.0,120.0,360.0,1.0,0,1,0,1,0,0,1
197,0.0,0,0.0,1907,2365.0,120.0,360.0,1.0,1,0,0,1,0,0,1
9,1.0,1,0.0,12841,10968.0,349.0,360.0,1.0,0,1,1,0,0,1,0
250,1.0,0,0.0,1668,3890.0,201.0,360.0,0.0,0,1,0,1,0,1,0
304,0.0,0,0.0,4000,2500.0,140.0,360.0,1.0,0,1,1,0,1,0,0
483,1.0,0,0.0,10833,0.0,234.0,360.0,1.0,0,1,1,0,0,1,0
474,0.0,2,0.0,5532,4648.0,162.0,360.0,1.0,0,1,1,0,1,0,0
341,0.0,0,0.0,2378,0.0,46.0,360.0,1.0,1,0,1,0,1,0,0
404,0.0,0,1.0,7441,0.0,194.0,360.0,1.0,1,0,1,0,1,0,0
247,1.0,1,0.0,6608,0.0,137.0,180.0,1.0,0,1,0,1,0,0,1
464,0.0,0,0.0,4166,0.0,98.0,360.0,0.0,0,1,1,0,0,1,0
493,0.0,0,1.0,17263,0.0,225.0,360.0,1.0,1,0,0,1,0,1,0

In [33]:
y_predicted

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [34]:
model.predict_proba(X_test)

array([[0.1571838 , 0.8428162 ],
       [0.15546362, 0.84453638],
       [0.30816511, 0.69183489],
       [0.29876218, 0.70123782],
       [0.11997483, 0.88002517],
       [0.9351551 , 0.0648449 ],
       [0.07582307, 0.92417693],
       [0.34600872, 0.65399128],
       [0.26050919, 0.73949081],
       [0.87671362, 0.12328638],
       [0.22062021, 0.77937979],
       [0.13371604, 0.86628396],
       [0.15832277, 0.84167723],
       [0.30883008, 0.69116992],
       [0.29675006, 0.70324994],
       [0.18098545, 0.81901455],
       [0.15729491, 0.84270509],
       [0.1696835 , 0.8303165 ],
       [0.19960974, 0.80039026],
       [0.28639954, 0.71360046],
       [0.16021978, 0.83978022],
       [0.12381205, 0.87618795],
       [0.30648221, 0.69351779],
       [0.14946253, 0.85053747],
       [0.12579427, 0.87420573],
       [0.25631753, 0.74368247],
       [0.24955508, 0.75044492],
       [0.81355914, 0.18644086],
       [0.14398432, 0.85601568],
       [0.19162858, 0.80837142],
       [0.40251388, 0.59748612],
       [0.32286307, 0.67713693],
       [0.24494386, 0.75505614],
       [0.72196804, 0.27803196],
       [0.30436867, 0.69563133],
       [0.20673074, 0.79326926],
       [0.17474493, 0.82525507],
       [0.19852187, 0.80147813],
       [0.17350962, 0.82649038],
       [0.38395334, 0.61604666],
       [0.25763937, 0.74236063],
       [0.16892318, 0.83107682],
       [0.24795213, 0.75204787],
       [0.19641538, 0.80358462],
       [0.22739959, 0.77260041],
       [0.19121632, 0.80878368],
       [0.1978104 , 0.8021896 ],
       [0.91874109, 0.08125891],
       [0.11726168, 0.88273832],
       [0.1607832 , 0.8392168 ],
       [0.28795938, 0.71204062],
       [0.38286887, 0.61713113],
       [0.24074101, 0.75925899],
       [0.22844091, 0.77155909],
       [0.13357173, 0.86642827],
       [0.69932364, 0.30067636],
       [0.16255566, 0.83744434],
       [0.96362961, 0.03637039],
       [0.14857191, 0.85142809],
       [0.28939642, 0.71060358],
       [0.1717163 , 0.8282837 ],
       [0.20705075, 0.79294925],
       [0.24798253, 0.75201747],
       [0.74673603, 0.25326397],
       [0.92606994, 0.07393006],
       [0.27135973, 0.72864027],
       [0.13564552, 0.86435448],
       [0.26056176, 0.73943824],
       [0.20000494, 0.79999506],
       [0.10226804, 0.89773196],
       [0.13724266, 0.86275734],
       [0.08461579, 0.91538421],
       [0.17048438, 0.82951562],
       [0.89996182, 0.10003818],
       [0.25255886, 0.74744114],
       [0.32092251, 0.67907749],
       [0.39683099, 0.60316901],
       [0.22655934, 0.77344066],
       [0.93857959, 0.06142041],
       [0.90755248, 0.09244752],
       [0.76761773, 0.23238227],
       [0.26651076, 0.73348924],
       [0.30513697, 0.69486303],
       [0.32278308, 0.67721692],
       [0.32147811, 0.67852189],
       [0.2135167 , 0.7864833 ],
       [0.23736092, 0.76263908],
       [0.12874907, 0.87125093],
       [0.13913189, 0.86086811],
       [0.23153776, 0.76846224],
       [0.92966872, 0.07033128],
       [0.37956588, 0.62043412],
       [0.22615583, 0.77384417],
       [0.12571745, 0.87428255],
       [0.08793892, 0.91206108],
       [0.25413453, 0.74586547],
       [0.27887734, 0.72112266],
       [0.18229357, 0.81770643],
       [0.1049196 , 0.8950804 ],
       [0.28944159, 0.71055841],
       [0.26758929, 0.73241071],
       [0.13890236, 0.86109764],
       [0.14037619, 0.85962381],
       [0.11522173, 0.88477827],
       [0.22034831, 0.77965169],
       [0.14968767, 0.85031233],
       [0.12526072, 0.87473928],
       [0.19001432, 0.80998568],
       [0.8761126 , 0.1238874 ],
       [0.17270601, 0.82729399],
       [0.23548888, 0.76451112],
       [0.34050384, 0.65949616],
       [0.41319923, 0.58680077],
       [0.2100987 , 0.7899013 ],
       [0.87819532, 0.12180468],
       [0.3219795 , 0.6780205 ],
       [0.12412251, 0.87587749],
       [0.3054414 , 0.6945586 ],
       [0.25119567, 0.74880433],
       [0.29037752, 0.70962248],
       [0.19838951, 0.80161049],
       [0.83516678, 0.16483322],
       [0.23479564, 0.76520436]])

In [35]:
model.score(X_test,y_test)

0.8048780487804879

In [36]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predicted)

0.8048780487804879

# random forest

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=1)

In [38]:
from sklearn.ensemble import RandomForestClassifier
regressor=RandomForestClassifier()
regressor.fit(X_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [39]:
y_pred=regressor.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[18 21]
 [11 73]]
0.7398373983739838

In [41]:
regressor.score(X_test,y_test)

0.7398373983739838

# decision tree

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=1)

In [43]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [44]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [45]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1], dtype=int64)

In [46]:
y_test

     Loan_Status
533            0
544            1
41             1
148            0
111            1
293            0
435            1
407            1
311            1
23             0
242            1
185            1
521            1
496            1
566            1
301            1
375            1
200            1
599            1
306            1
132            1
559            1
0              1
135            0
195            0
386            1
563            1
201            1
520            1
518            0
..           ...
223            1
574            0
425            1
92             1
295            1
484            1
260            1
268            0
103            1
560            1
224            1
187            1
80             1
516            1
379            1
373            0
436            1
545            1
3              1
197            1
9              0
250            0
304            1
483            1
474            1
341            0
404            0
247            1
464            0
493            1

[123 rows x 1 columns]

In [47]:
model.score(X_test,y_test)

0.7154471544715447

# SVM

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=1)

In [49]:
from sklearn.svm import SVC
model=SVC()

In [50]:
model.fit(X_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [51]:
model.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [52]:
model.score(X_test,y_test)

0.6829268292682927